use_frameworks!

platform :ios, '8.0'

target 'HHChatKit_Example' do
  pod 'HHChatKit', :path => '../'

  target 'HHChatKit_Tests' do
    inherit! :search_paths

    pod 'Specta'
    pod 'Expecta'
    pod 'FBSnapshotTestCase'
    pod 'Expecta+Snapshots'
  end
end
